version: "3.8"
services:
  db:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - coinly_network
  app:
    image: "coinly-app"
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - coinly_network

networks:
  coinly_network:
    driver: bridge