version: "3.8"
services:
  db:
    image: coinly-db
    build:
      dockerfile: ./db/Dockerfile
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    image: coinly-app
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"