# Use the official PostgreSQL image
FROM postgres:12

# Expose PostgreSQL port
EXPOSE 5432

# If you would like to keep your container running in detached mode, you need to run something in the foreground.
# https://phpfog.com/how-to-keep-docker-containers-running/
CMD tail -f /dev/null