name: Testing the web application

on: push

jobs:
  testing:
    runs-on: ubuntu-22.04
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Installing dependencies
        run: |
          npm ci

      - name: Unit tests
        run: npm run test

      - name: Create env file
        run: |
          touch .env
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> .env
          echo 'AUTH_SECRET=${{ secrets.AUTH_SECRET }}' >> .env
          echo 'AUTH_URL=${{ secrets.AUTH_URL }}' >> .env
          cat .env

      - name: Set up web application
        run: |
          docker-compose up --build -d
          npx prisma migrate dev --name init
          npx prisma db seed
        
      - name: End-to-end tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}