name: Cypress Tests with Dependency and Artifact Caching

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> .env
          echo 'AUTH_SECRET=${{ secrets.AUTH_SECRET }}' >> .env
          echo '=${{ secrets.AUTH_URL }}' >> .env
          cat .env
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}