name: Testing web application

on: push

jobs:
  checkout-and-install:
    runs-on: ubuntu-22.04
    environment: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm ci

  unit-tests:
    runs-on: ubuntu-22.04
    environment: testing
    needs: checkout-and-install
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run Jest unit tests
        run: npm run test

  create-env-file:
    runs-on: ubuntu-22.04
    environment: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Generate Environment File
        run: |
          touch .env
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> .env
          echo 'AUTH_SECRET=${{ secrets.AUTH_SECRET }}' >> .env
          echo 'AUTH_URL=${{ secrets.AUTH_URL }}' >> .env
          cat .env

  setup-database:
    runs-on: ubuntu-22.04
    environment: testing
    needs: [checkout-and-install, create-env-file]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Database
        run: |
          docker-compose down && docker-compose up -d
          npx prisma migrate dev --name init
          npx prisma db seed

  run-cypress-tests:
    runs-on: ubuntu-22.04
    environment: testing
    needs: [checkout-and-install, create-env-file, setup-database]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
